// Evidence items for offers 1-5 (buyer-evidence researcher, 2026-10-10). Quotes are fragments seen in search-result text for each URL; none could be fetched from this session.
export const ITEMS_01_05 = [
  // Offer 1: missed-call follow-up
  { id: "o1-hatch-run-rate-sec-letter", offer: "missed-call-follow-up", shows: "Yelp's SEC-filed Q2 2026 shareholder letter reports that Hatch, the AI lead follow-up platform for services businesses that Yelp bought, grew annual run-rate revenue 59% to $35 million (spend on lead follow-up software in general, not on this offer).", url: "https://www.sec.gov/Archives/edgar/data/0001345016/000134501626000059/yelpq22026ex992lettertos.htm", quote: "59% year over year to $35 million in June", kind: "paid-demand" },
  { id: "o1-hatch-acquisition-price", offer: "missed-call-follow-up", shows: "Yelp's press release states the price it agreed to pay for Hatch, an AI lead-management platform for services businesses: about $270 million in cash.", url: "https://www.yelp-ir.com/news/press-releases/news-release-details/2026/Yelp-Accelerates-Strategy-with-Acquisition-of-AI-Lead-Management-Platform-Hatch/default.aspx", quote: "$270 million in cash", kind: "paid-demand" },
  { id: "o1-ruby-receptionist-pricing", offer: "missed-call-follow-up", shows: "Ruby's pricing page lists a $1,725 plan (its 500-minute monthly live-receptionist plan, per the search snippet); an asking price, not a sale.", url: "https://www.ruby.com/plans-and-pricing/", quote: "$1,725", kind: "price" },
  { id: "o1-jobber-ai-receptionist-allowance", offer: "missed-call-follow-up", shows: "Jobber's help article for its paid AI Receptionist add-on states an included allowance of 30 conversations (the snippet gave the add-on price as $29 per month, which this quote does not itself show).", url: "https://help.getjobber.com/hc/en-us/articles/25315927533847-Receptionist-powered-by-Jobber-AI", quote: "30 conversations", kind: "price" },
  { id: "o1-plumber-answering-service-450", offer: "missed-call-follow-up", shows: "A plumber on the PlumbingZone forum says his answering service costs about $450 a month (one owner's old post; buyer-side spend on answering calls).", url: "https://www.plumbingzone.com/threads/anyone-have-any-advice-for-hiring-an-answering-service.31658/", quote: "$450 a month", kind: "paid-demand" },
  { id: "o1-plumber-47-missed-calls", offer: "missed-call-follow-up", shows: "A small plumbing business owner on PlumbingZone reports 47 missed calls in one month (his own count).", url: "https://www.plumbingzone.com/threads/anyone-else-losing-jobs-to-missed-calls.91027/", quote: "47 missed calls last month", kind: "buyer-words" },
  { id: "o1-missed-calls-mostly-telemarketers", offer: "missed-call-follow-up", shows: "A later post in the same thread says 40 of those missed calls were telemarketers, so most missed calls were not lost leads (a caveat on the size of the problem).", url: "https://www.plumbingzone.com/threads/anyone-else-losing-jobs-to-missed-calls.91027/", quote: "40 of them were telemarketers", kind: "buyer-words" },

  // Offer 2: stale estimate follow-up
  { id: "o2-jobber-pricing-quote-follow-ups", offer: "stale-estimate-follow-up", shows: "Jobber's pricing page lists automated quote and invoice follow-ups as a feature of its paid plans (the Connect tier and up, per the snippets); a listed feature, not proof of use.", url: "https://www.getjobber.com/pricing/", quote: "Automate quote and invoice follow-ups", kind: "price" },
  { id: "o2-allied-roofing-follow-up-wage", offer: "stale-estimate-follow-up", shows: "A roofing contractor's job post offers $10 to $15 an hour for a remote inside-sales role centred on customer follow-up (a posted wage for follow-up work, not specifically estimate follow-up).", url: "https://alliedroofingconstruction.discovered.ai/job-details/69946", quote: "$15.00 per hour", kind: "paid-demand" },
  { id: "o2-servicetitan-unsold-estimates-coordinator", offer: "stale-estimate-follow-up", shows: "A ServiceTitan customer story (vendor content) says a roughly $20M contractor's dedicated follow-up coordinator brought in $1 million from unsold estimates in 2024 (the company's own claim).", url: "https://www.servicetitan.com/blog/success-story-above-beyond-field-pro", quote: "$1 million in revenue from unsold estimates", kind: "paid-demand" },
  { id: "o2-hatch-estimate-campaigns", offer: "stale-estimate-follow-up", shows: "Hatch's blog (vendor data) says it analysed 163,000 HVAC two-day estimate follow-up campaigns.", url: "https://www.usehatchapp.com/blog/hvac-estimate-follow-up-response-rates", quote: "163,000", kind: "other" },
  { id: "o2-housecall-pro-pipeline-follow-up", offer: "stale-estimate-follow-up", shows: "Housecall Pro's help center documents a built-in automation that resends unanswered estimates and marks them First Follow-Up (a competing feature, not evidence of spend).", url: "https://help.housecallpro.com/en/articles/6185127-getting-started-with-pipeline", quote: "update status to First Follow-Up", kind: "other" },
  { id: "o2-jobber-community-unscheduled-quotes", offer: "stale-estimate-follow-up", shows: "Jobber users have a community thread on how they follow up on unscheduled quotes (buyers discuss the problem; not evidence of spend).", url: "https://community.getjobber.com/discussions/marketing-forum/what%E2%80%99s-your-process-for-following-up-on-unscheduled-quotes/2237", quote: "following up on unscheduled quotes", kind: "buyer-words" },
  { id: "o2-contractortalk-silence-after-quotes", offer: "stale-estimate-follow-up", shows: "A ContractorTalk thread is titled 'Silence after giving quotes', a contractor describing quotes that go unanswered.", url: "https://www.contractortalk.com/threads/silence-after-giving-quotes.196530/", quote: "Silence after giving quotes", kind: "buyer-words" },

  // Offer 3: job-cost exceptions
  { id: "o3-catalyst-construction-bookkeeping-price", offer: "job-cost-exceptions", shows: "Catalyst CPA's construction bookkeeping page states a monthly fee that runs up to $1,200 depending on job volume (job costing and WIP are in its scope per the snippet); an asking price, not a sale.", url: "https://catalyst-cpa.com/construction-bookkeeping/", quote: "$1,200/month depending on job volume", kind: "price" },
  { id: "o3-qb-community-project-costing", offer: "job-cost-exceptions", shows: "A QuickBooks user titled a community thread 'PROJECT COSTING DOES NOT WORK PERIOD', complaining that project-costing reports are inaccurate.", url: "https://quickbooks.intuit.com/learn-support/en-us/reports-and-accounting/project-costing-does-not-work-period-again-inaccurate-reporting/00/1319526", quote: "PROJECT COSTING DOES NOT WORK PERIOD", kind: "buyer-words" },
  { id: "o3-qb-community-job-profitability", offer: "job-cost-exceptions", shows: "A QuickBooks user reports that the Job Profitability Report is still not right (buyer words about wrong job-cost reports).", url: "https://quickbooks.intuit.com/learn-support/en-us/reports-and-accounting/job-profitability-report-still-not-right/00/1095737", quote: "Job Profitability Report still not right", kind: "buyer-words" },
  { id: "o3-contractortalk-estimates-vs-actuals", offer: "job-cost-exceptions", shows: "A contractor shopping for job-costing software says he wants to compare estimates with actuals over time to refine his quotes (buyer words about the need).", url: "https://www.contractortalk.com/threads/need-recommendation-for-job-costing-software.457514/", quote: "refine my quotes for similar jobs", kind: "buyer-words" },
  { id: "o3-contractortalk-knowify-job-costing", offer: "job-cost-exceptions", shows: "A contractor praises Knowify's job costing, which the same post prices at about $99/month (one buyer's opinion; the price is outside this quote).", url: "https://www.contractortalk.com/threads/need-recommendation-for-job-costing-software.457514/", quote: "job costing piece is really well done", kind: "buyer-words" },

  // Offer 4: receipt and invoice matching
  { id: "o4-dext-xero-reviews", offer: "receipt-invoice-matching", shows: "Dext, a paid receipt-capture tool, has 1116 reviews on its US Xero App Store listing (count as of the snippet; it drifts).", url: "https://apps.xero.com/us/app/dext/reviews", quote: "1116 Reviews", kind: "review-count" },
  { id: "o4-autoentry-xero-reviews", offer: "receipt-invoice-matching", shows: "AutoEntry, a paid document-capture tool, has 465 reviews on its US Xero App Store listing (count as of the snippet; it drifts).", url: "https://apps.xero.com/us/app/autoentry/reviews", quote: "465 Reviews", kind: "review-count" },
  { id: "o4-dext-business-pricing", offer: "receipt-invoice-matching", shows: "Dext's US business pricing page lists $25.21 (per month on annual billing, per the snippet); an asking price, not a sale.", url: "https://dext.com/us/business/pricing", quote: "$25.21", kind: "price" },
  { id: "o4-upwork-monthly-cleanup-budget", offer: "receipt-invoice-matching", shows: "An Upwork client posted monthly QuickBooks cleanup and reconciliation work with a $15.00 fixed-price budget (a posted budget, showing how low some buyers price this work).", url: "https://www.upwork.com/freelance-jobs/apply/Bookkeeper-for-monthly-QuickBooks-cleanup_~022101019768267243801/", quote: "$15.00", kind: "paid-demand" },
  { id: "o4-accountingweb-client-information-survey", offer: "receipt-invoice-matching", shows: "AccountingWEB reports a survey of UK practitioners in which 67% named getting information from clients as their biggest difficulty after the first MTD quarterly deadline (trade-press report of a survey).", url: "https://www.accountingweb.co.uk/tech/practice-software/reveal-sets-sights-on-ending-the-client-document-chase", quote: "67% cited getting information from clients", kind: "other" },
  { id: "o4-qb-community-missing-receipts-report", offer: "receipt-invoice-matching", shows: "A QuickBooks user asks how to see which categorized transactions have no receipt attached, the gap an exceptions list fills.", url: "https://quickbooks.intuit.com/learn-support/en-us/reports-and-accounting/is-there-a-way-to-see-which-categorized-transactions-don-t-have/00/1406619", quote: "which categorized transactions", kind: "buyer-words" },
  { id: "o4-qb-community-receipt-matching", offer: "receipt-invoice-matching", shows: "A QuickBooks user reports that matching receipts to bank transactions does not work for them.", url: "https://quickbooks.intuit.com/community/banking-4/receipt-matching-to-bank-transactions-doesn-t-work-24245", quote: "Receipt Matching to Bank Transactions", kind: "buyer-words" },

  // Offer 5: unpaid-invoice tracking
  { id: "o5-chaser-xero-reviews", offer: "unpaid-invoice-tracking", shows: "Chaser, a paid accounts-receivable reminder tool, has 374 reviews on its US Xero App Store listing (count as of the snippet; it drifts).", url: "https://apps.xero.com/us/app/chaser/reviews", quote: "374 Reviews", kind: "review-count" },
  { id: "o5-paidnice-xero-reviews", offer: "unpaid-invoice-tracking", shows: "Paidnice, a paid invoice-reminder tool, has 83 reviews on its US Xero App Store listing (count as of the snippet; it drifts).", url: "https://apps.xero.com/us/app/paidnice/reviews", quote: "83 Reviews", kind: "review-count" },
  { id: "o5-quickbooks-late-payments-extra-fees", offer: "unpaid-invoice-tracking", shows: "Intuit's 2026 late-payments survey (vendor research) reports that 59% of surveyed owners paid extra fees to get money they had already earned.", url: "https://quickbooks.intuit.com/r/small-business-data/small-business-late-payments-report-2026/", quote: "paid extra fees last year just to access money", kind: "paid-demand" },
  { id: "o5-quickbooks-late-payments-amount-owed", offer: "unpaid-invoice-tracking", shows: "Intuit's 2026 late-payments survey (vendor research) reports that businesses with unpaid invoices are owed an average of $17.7K.", url: "https://quickbooks.intuit.com/r/small-business-data/small-business-late-payments-report-2026/", quote: "owed an average of $17.7K", kind: "other" },
  { id: "o5-invoicesherpa-pricing-tier", offer: "unpaid-invoice-tracking", shows: "InvoiceSherpa's pricing page describes a paid plan tier sized at up to 100 open invoices ($49/month per the snippet, which this quote does not itself show); an asking price, not a sale.", url: "https://www.invoicesherpa.com/pricing", quote: "100 open invoices", kind: "price" },
  { id: "o5-paidnice-pricing-tier", offer: "unpaid-invoice-tracking", shows: "Paidnice's pricing page describes an Essentials tier sized at 150 invoices monitored per month (69 USD/month per the snippet, which this quote does not itself show); an asking price.", url: "https://www.paidnice.com/pricing", quote: "150 invoices monitored", kind: "price" },
  { id: "o5-qb-community-awful-reminders", offer: "unpaid-invoice-tracking", shows: "A QuickBooks user calls the built-in automatic invoice-reminder email awful and prefers their own template (buyer words about tone, not about spend).", url: "https://quickbooks.intuit.com/learn-support/en-us/reports-and-accounting/how-do-i-turn-off-the-feature-that-generates-emails-for-invoice/00/1498858", quote: "It is AWFUL and I would never send an email like this", kind: "buyer-words" },
];
