const CHECKED = "2026-08-28";

export type CatalogEntry = {
  slug: string;
  name: string;
  website: string;
  research: Record<string, unknown>;
  score: Record<string, number>;
  defaultStatus: "connected" | "needs_mike" | "rejected" | "discovered";
  automationAllowed: string;
  accessMethods: string;
  rejectReason?: string;
  rejectCategory?: string;
};

/** Official-doc research. Marketing copy is not used as the sole source. */
export const PLATFORM_CATALOG: CatalogEntry[] = [
  {
    slug: "taskbounty",
    name: "TaskBounty",
    website: "https://www.task-bounty.com",
    automationAllowed: "yes",
    accessMethods: "API, MCP",
    defaultStatus: "connected",
    score: { profitability: 70, reliability: 75, automation: 90, risk: 35, volume: 20, capability: 85 },
    research: {
      officialWebsite: "https://www.task-bounty.com",
      terms: "https://www.task-bounty.com/terms",
      termsDate: "2026-04-17",
      agentsPermitted: true,
      automationPermitted: true,
      apiMcp: "https://www.task-bounty.com/docs/mcp",
      browserAutomation: "Device login /link permitted; scraping the site beyond rate limits is prohibited (ToS §11e).",
      typicalPayout: "$10–few hundred; solver receives 80%",
      platformFees: "20%",
      payoutMethod: "USDC/ETH/BTC or USD bank via dashboard (bank = owner)",
      payoutMinimum: "First payout immediate; then $50 monthly batch",
      identityTax: "Bank/Stripe Connect and tax forms are owner-only",
      geo: "18+; sanctioned jurisdictions barred",
      expectedCost: "Compute to produce a real patch + regression test",
      checkedAt: CHECKED,
      sources: [
        "https://www.task-bounty.com/terms",
        "https://www.task-bounty.com/for-agents",
        "https://www.task-bounty.com/docs/mcp",
      ],
    },
  },
  {
    slug: "sporeagent",
    name: "SporeAgent",
    website: "https://sporeagent.com",
    automationAllowed: "yes",
    accessMethods: "API, MCP",
    defaultStatus: "needs_mike",
    score: { profitability: 45, reliability: 50, automation: 80, risk: 45, volume: 40, capability: 35 },
    research: {
      officialWebsite: "https://sporeagent.com",
      terms: "https://sporeagent.com/docs",
      agentsPermitted: true,
      automationPermitted: true,
      apiMcp: "https://sporeagent.com/mcp and REST /api/tasks",
      browserAutomation: "Unknown; API/MCP is the documented path",
      typicalPayout: "Listed USD budgets (live board varies)",
      platformFees: "Not published — treat as unknown (conservative 10% in profit engine)",
      payoutMethod: "Account payout on their dashboard if shown",
      identityTax: "Existing agent id required; do not spore_register a duplicate",
      checkedAt: CHECKED,
      sources: ["https://sporeagent.com/docs", "https://sporeagent.com/api/health"],
    },
  },
  {
    slug: "moltjobs",
    name: "MoltJobs",
    website: "https://moltjobs.io",
    automationAllowed: "yes",
    accessMethods: "API, MCP, CLI",
    defaultStatus: "needs_mike",
    score: { profitability: 25, reliability: 40, automation: 85, risk: 55, volume: 50, capability: 40 },
    research: {
      officialWebsite: "https://moltjobs.io",
      agentsPermitted: true,
      automationPermitted: true,
      apiMcp: "https://api.moltjobs.io/v1/jobs — MCP + npx @moltjobs/cli",
      browserAutomation: "Dashboard signup is human; work is API-first",
      typicalPayout: "Live board includes $2–$5 USDC promo/lead tasks (verified 2026-08-28)",
      platformFees: "5% escrow fee on funded jobs (marketing page; treat as unverified until invoice)",
      payoutMethod: "USDC on Base — public address only; wallet = owner",
      payoutMinimum: "Unknown",
      identityTax: "Register agent + API key mj_live_ + wallet",
      expectedCost: "Many current jobs are paid social posts requiring a human account — reject those",
      checkedAt: CHECKED,
      sources: ["https://moltjobs.io/", "https://api.moltjobs.io/v1/jobs?status=OPEN"],
    },
  },
  {
    slug: "workprotocol",
    name: "WorkProtocol",
    website: "https://workprotocol.ai",
    automationAllowed: "yes",
    accessMethods: "API, MCP, RSS/Atom, A2A",
    defaultStatus: "needs_mike",
    score: { profitability: 40, reliability: 45, automation: 90, risk: 45, volume: 25, capability: 55 },
    research: {
      officialWebsite: "https://workprotocol.ai",
      agentsPermitted: true,
      automationPermitted: true,
      apiMcp: "https://workprotocol.ai/api/openapi.json — REST claim/deliver + /api/mcp",
      browserAutomation: "Register via API; human dashboard optional",
      typicalPayout: "Listed USD/USDC on open jobs (board often sparse)",
      platformFees: "~5% (treat as unverified until invoice)",
      payoutMethod: "USDC on Base and/or Stripe rail per job",
      payoutMinimum: "Amber enforces $5 minimum payout",
      identityTax: "POST /api/agents/register returns agent id + apiKey once — Amber auto-registers and stores both",
      expectedCost: "Reject watch-video / engagement farms; deliverable must be a public URL",
      checkedAt: CHECKED,
      sources: [
        "https://workprotocol.ai/api/openapi.json",
        "https://workprotocol.ai/api/jobs?status=open",
        "https://workprotocol.ai/api/health",
      ],
    },
  },
  {
    slug: "reelo_services",
    name: "Reelo paid services",
    website: "https://www.myreelo.com",
    automationAllowed: "yes",
    accessMethods: "Internal",
    defaultStatus: "connected",
    score: { profitability: 60, reliability: 80, automation: 70, risk: 20, volume: 0, capability: 90 },
    research: {
      officialWebsite: "https://www.myreelo.com",
      agentsPermitted: true,
      automationPermitted: true,
      note: "Website audits, lead-gen, and digital products Amber already operates. No inbound paid orders until a customer pays. Do not invent demand.",
      typicalPayout: "Customer invoices — $0 until a real order exists",
      platformFees: "Stripe if billed",
      payoutMethod: "Existing Reelo Stripe",
      checkedAt: CHECKED,
      sources: ["https://www.myreelo.com/business-center/pro"],
    },
  },
  {
    slug: "amazon_mturk",
    name: "Amazon Mechanical Turk",
    website: "https://www.mturk.com",
    automationAllowed: "no",
    accessMethods: "none",
    defaultStatus: "rejected",
    rejectCategory: "automation_prohibited",
    rejectReason: "Requester/worker TOS treat unattended bots as prohibited. Not a permitted AI-agent marketplace.",
    score: { profitability: 20, reliability: 60, automation: 5, risk: 80, volume: 50, capability: 20 },
    research: {
      officialWebsite: "https://www.mturk.com",
      agentsPermitted: false,
      automationPermitted: false,
      checkedAt: CHECKED,
      sources: ["https://www.mturk.com/worker/help"],
    },
  },
  {
    slug: "dataannotation",
    name: "DataAnnotation",
    website: "https://www.dataannotation.tech",
    automationAllowed: "no",
    accessMethods: "none",
    defaultStatus: "rejected",
    rejectCategory: "automation_prohibited",
    rejectReason: "Human labeling work; using an AI/bot to complete tasks misrepresents the worker.",
    score: { profitability: 30, reliability: 50, automation: 5, risk: 85, volume: 40, capability: 10 },
    research: {
      officialWebsite: "https://www.dataannotation.tech",
      agentsPermitted: false,
      automationPermitted: false,
      checkedAt: CHECKED,
      sources: ["https://www.dataannotation.tech"],
    },
  },
];
