export type SourcePolicy = {
  slug: string;
  name: string;
  url: string;
  sourceType: string;
  dataType: string;
  publicPrivate: "public" | "private";
  apiAvailable: boolean;
  feedAvailable: boolean;
  permittedAutomation: "yes" | "no" | "manual_only";
  scrapingStatus: "permitted" | "prohibited" | "unknown";
  attribution: string;
  commercialUse: string;
  refreshLimit: string;
  rateLimit: string;
  lastTermsReview: string;
  reliability: number;
  defaultActive: boolean;
  needsMike?: string;
};

const REVIEWED = "2026-08-28";

export const SOURCE_CATALOG: SourcePolicy[] = [
  {
    slug: "sfgov_assessor",
    name: "SF Open Data — Assessor-Recorder Property Information",
    url: "https://data.sfgov.org/resource/wv5m-vpq2.json",
    sourceType: "government_open_data",
    dataType: "assessor_parcels",
    publicPrivate: "public",
    apiAvailable: true,
    feedAvailable: true,
    permittedAutomation: "yes",
    scrapingStatus: "permitted",
    attribution: "City and County of San Francisco, Assessor-Recorder (Socrata SODA).",
    commercialUse: "Open data; follow SF Open Data terms.",
    refreshLimit: "Daily",
    rateLimit: "SODA default; 40 rows/tick",
    lastTermsReview: REVIEWED,
    reliability: 82,
    defaultActive: true,
  },
  {
    slug: "lacounty_assessor",
    name: "Los Angeles County Assessor — Parcel Roll (public GIS)",
    url: "https://public.gis.lacounty.gov/public/rest/services/LACounty_Cache/LACounty_Parcel/MapServer/0",
    sourceType: "government_open_data",
    dataType: "assessor_parcels",
    publicPrivate: "public",
    apiAvailable: true,
    feedAvailable: true,
    permittedAutomation: "yes",
    scrapingStatus: "permitted",
    attribution: "County of Los Angeles Assessor public GIS (LACounty_Parcel MapServer).",
    commercialUse: "County public GIS; follow LA County GIS terms. No owner names stored.",
    refreshLimit: "Daily",
    rateLimit: "ArcGIS query; 12 rows/tick",
    lastTermsReview: REVIEWED,
    reliability: 80,
    defaultActive: true,
  },
  {
    slug: "ca_statewide_parcels",
    name: "California statewide parcel GIS — all 58 counties",
    url: "https://gis.water.ca.gov/arcgis/rest/services/Planning/i15_Parcels_Assessor_Lightbox/MapServer/0",
    sourceType: "government_open_data",
    dataType: "assessor_parcels_statewide",
    publicPrivate: "public",
    apiAvailable: true,
    feedAvailable: true,
    permittedAutomation: "yes",
    scrapingStatus: "permitted",
    attribution:
      "County assessor/GIS public FeatureServer layers where published. Remaining counties: California DWR GIS Atlas i15 Parcels Assessor Lightbox (identity/address only; originator LightBox; no owner or tax fields requested or stored).",
    commercialUse:
      "County public GIS and DWR GIS Atlas public query. Identity/address only. Not a title search. One blocked county does not stop others.",
    refreshLimit: "Each scan visits a batch of the 58 counties; cron rotates until every county is visited",
    rateLimit: "8 county layers/tick (~8 rows each); Buy Box counties prioritized, then alphabetical rotation through all 58",
    lastTermsReview: REVIEWED,
    reliability: 75,
    defaultActive: true,
  },
  {
    slug: "lacity_business",
    name: "City of LA Open Data — Business Licenses",
    url: "https://data.lacity.org/resource/6rrh-rzua.json",
    sourceType: "government_open_data",
    dataType: "business_licenses_investor_prospects",
    publicPrivate: "public",
    apiAvailable: true,
    feedAvailable: true,
    permittedAutomation: "yes",
    scrapingStatus: "permitted",
    attribution: "City of Los Angeles Open Data (Socrata SODA).",
    commercialUse: "Open data; follow LA Open Data terms.",
    refreshLimit: "Daily",
    rateLimit: "SODA default; 25 rows/tick",
    lastTermsReview: REVIEWED,
    reliability: 70,
    defaultActive: true,
  },
  {
    slug: "sbcounty_tax_default",
    name: "San Bernardino County TTC — Defaulted Bills (open data)",
    url: "https://opendata.sbcountyatc.gov/",
    sourceType: "government_open_data",
    dataType: "tax_defaulted_bills",
    publicPrivate: "public",
    apiAvailable: true,
    feedAvailable: true,
    permittedAutomation: "yes",
    scrapingStatus: "permitted",
    attribution: "San Bernardino County Treasurer-Tax Collector Open Data (official CSV feed).",
    commercialUse: "County open data; follow TTC open-data terms.",
    refreshLimit: "Weekly (county publishes Sundays)",
    rateLimit: "Ranged CSV read ~28KB/tick; do not download full 54MB file each tick",
    lastTermsReview: REVIEWED,
    reliability: 86,
    defaultActive: true,
  },
  {
    slug: "sfttc_tax_sale",
    name: "SF Treasurer-Tax Collector — 2026 tax-defaulted property auction notice",
    url: "https://sftreasurer.org/file/2026-public-and-sealed-bid-auction-publication/download?attachment=",
    sourceType: "government_open_data",
    dataType: "tax_defaulted_auction_notice",
    publicPrivate: "public",
    apiAvailable: true,
    feedAvailable: true,
    permittedAutomation: "yes",
    scrapingStatus: "permitted",
    attribution: "City and County of San Francisco Office of the Treasurer & Tax Collector, official 2026 tax-defaulted property auction publication. Assessee names are not stored.",
    commercialUse: "Official public auction notice; follow SF TTC terms. Not a title search.",
    refreshLimit: "Each published auction notice",
    rateLimit: "One PDF (~220KB) per scan",
    lastTermsReview: REVIEWED,
    reliability: 92,
    defaultActive: true,
  },
  {
    slug: "census_acs",
    name: "U.S. Census ACS 5-year (CA counties)",
    url: "https://api.census.gov/data/2023/acs/acs5",
    sourceType: "government_api",
    dataType: "market_stats",
    publicPrivate: "public",
    apiAvailable: true,
    feedAvailable: false,
    permittedAutomation: "yes",
    scrapingStatus: "permitted",
    attribution: "U.S. Census Bureau ACS.",
    commercialUse: "Public data; Census API key required (free).",
    refreshLimit: "Annual vintage",
    rateLimit: "Census API key limits",
    lastTermsReview: REVIEWED,
    reliability: 90,
    defaultActive: false,
    needsMike: "Free Census API key (CENSUS_API_KEY). Not a paid subscription — owner must accept Census terms.",
  },
  {
    slug: "hud_fmr",
    name: "HUD Fair Market Rents",
    url: "https://www.huduser.gov/portal/datasets/fmr.html",
    sourceType: "government_api",
    dataType: "estimated_rent",
    publicPrivate: "public",
    apiAvailable: true,
    feedAvailable: true,
    permittedAutomation: "yes",
    scrapingStatus: "permitted",
    attribution: "U.S. Department of Housing and Urban Development.",
    commercialUse: "Public data; HUD User token is free registration.",
    refreshLimit: "Annual",
    rateLimit: "HUD API token limits",
    lastTermsReview: REVIEWED,
    reliability: 88,
    defaultActive: false,
    needsMike: "OWNER REVIEW — PAID DATA SOURCE? No. Free HUD User token signup still requires owner identity/terms acceptance.",
  },
  {
    slug: "zillow",
    name: "Zillow (public website)",
    url: "https://www.zillow.com",
    sourceType: "commercial_website",
    dataType: "listings",
    publicPrivate: "private",
    apiAvailable: false,
    feedAvailable: false,
    permittedAutomation: "no",
    scrapingStatus: "prohibited",
    attribution: "Zillow terms prohibit unauthorized automated collection.",
    commercialUse: "Licensed API/feed only — not enabled.",
    refreshLimit: "n/a",
    rateLimit: "n/a",
    lastTermsReview: REVIEWED,
    reliability: 0,
    defaultActive: false,
  },
  {
    slug: "redfin",
    name: "Redfin (public website)",
    url: "https://www.redfin.com",
    sourceType: "commercial_website",
    dataType: "listings",
    publicPrivate: "private",
    apiAvailable: false,
    feedAvailable: false,
    permittedAutomation: "no",
    scrapingStatus: "prohibited",
    attribution: "Do not scrape.",
    commercialUse: "Not authorized.",
    refreshLimit: "n/a",
    rateLimit: "n/a",
    lastTermsReview: REVIEWED,
    reliability: 0,
    defaultActive: false,
  },
  {
    slug: "realtor",
    name: "Realtor.com (public website)",
    url: "https://www.realtor.com",
    sourceType: "commercial_website",
    dataType: "listings",
    publicPrivate: "private",
    apiAvailable: false,
    feedAvailable: false,
    permittedAutomation: "no",
    scrapingStatus: "prohibited",
    attribution: "Do not scrape.",
    commercialUse: "Not authorized.",
    refreshLimit: "n/a",
    rateLimit: "n/a",
    lastTermsReview: REVIEWED,
    reliability: 0,
    defaultActive: false,
  },
  {
    slug: "ca_nod_trustee_reo",
    name: "NOD / trustee sale / REO commercial feeds",
    url: "",
    sourceType: "commercial_feed",
    dataType: "distressed_filings",
    publicPrivate: "private",
    apiAvailable: false,
    feedAvailable: false,
    permittedAutomation: "no",
    scrapingStatus: "prohibited",
    attribution: "No free statewide NOD/trustee/REO API. Paid foreclosure services are not enabled.",
    commercialUse: "Not authorized. Do not scrape recorder sites or listing portals.",
    refreshLimit: "n/a",
    rateLimit: "n/a",
    lastTermsReview: REVIEWED,
    reliability: 0,
    defaultActive: false,
  },
];
