// ---------------------------------------------------------------------------
// The character catalog to generate.
//
// Each entry is [displayName, subject, primary, secondary[], tags[]].
//
// `subject` exists separately from `displayName` because names are ambiguous:
// "Peach" generated Princess Peach — a trademarked Nintendo character — rather
// than a peach. The subject spells out exactly what to draw, and every one is
// described as an ORIGINAL character so nothing resembles a real franchise.
// ---------------------------------------------------------------------------

export const CHARACTERS = [
  // --- fruit ----------------------------------------------------------------
  ["Apple", "a ripe red apple fruit with a friendly cartoon face", "fruit", ["food"], ["fruit", "healthy", "red"]],
  ["Banana", "a yellow banana fruit with a friendly cartoon face", "fruit", ["food"], ["fruit", "yellow"]],
  ["Orange", "a round orange citrus fruit with a friendly cartoon face", "fruit", ["food"], ["fruit", "citrus"]],
  ["Strawberry", "a red strawberry fruit with green leaves and a friendly cartoon face", "fruit", ["food"], ["fruit", "berry", "red"]],
  ["Watermelon", "a green watermelon fruit with a friendly cartoon face", "fruit", ["food"], ["fruit", "summer"]],
  ["Pineapple", "a golden pineapple fruit with a spiky green crown and a friendly cartoon face", "fruit", ["food"], ["fruit", "tropical"]],
  ["Grapes", "a bunch of purple grapes with a friendly cartoon face", "fruit", ["food"], ["fruit", "purple"]],
  ["Lemon", "a yellow lemon citrus fruit with a friendly cartoon face", "fruit", ["food"], ["fruit", "citrus", "yellow"]],
  ["Peach Fruit", "a round pink-orange peach FRUIT with a fuzzy skin and a friendly cartoon face, absolutely not a person or princess", "fruit", ["food"], ["fruit"]],
  ["Cherry", "a pair of red cherries on a stem with a friendly cartoon face", "fruit", ["food"], ["fruit", "berry", "red"]],
  ["Mango", "a ripe mango fruit with a friendly cartoon face", "fruit", ["food"], ["fruit", "tropical"]],
  ["Avocado", "a green avocado fruit cut in half with a stone, with a friendly cartoon face", "fruit", ["food"], ["fruit", "green", "healthy"]],
  ["Blueberry", "a plump blue blueberry fruit with a friendly cartoon face", "fruit", ["food"], ["fruit", "berry", "blue"]],
  ["Pear", "a green pear fruit with a friendly cartoon face", "fruit", ["food"], ["fruit", "green"]],
  ["Kiwi Fruit", "a sliced green kiwi fruit with a friendly cartoon face", "fruit", ["food"], ["fruit", "green"]],
  ["Coconut", "a brown coconut with a friendly cartoon face", "fruit", ["food"], ["fruit", "tropical"]],
  ["Raspberry", "a red raspberry fruit with a friendly cartoon face", "fruit", ["food"], ["fruit", "berry"]],
  ["Pomegranate", "a red pomegranate fruit with a friendly cartoon face", "fruit", ["food"], ["fruit", "red"]],

  // --- vegetables -----------------------------------------------------------
  ["Carrot", "an orange carrot vegetable with green leafy top and a friendly cartoon face", "vegetables", ["food"], ["vegetable", "orange", "healthy"]],
  ["Broccoli", "a green broccoli floret vegetable with a friendly cartoon face", "vegetables", ["food"], ["vegetable", "green", "healthy"]],
  ["Tomato", "a round red tomato with a friendly cartoon face", "vegetables", ["food"], ["vegetable", "red"]],
  ["Corn Cob", "a yellow corn cob with green husk and a friendly cartoon face", "vegetables", ["food"], ["vegetable", "yellow"]],
  ["Potato", "a brown potato with a friendly cartoon face", "vegetables", ["food"], ["vegetable"]],
  ["Bell Pepper", "a shiny red bell pepper vegetable with a friendly cartoon face", "vegetables", ["food"], ["vegetable", "red"]],
  ["Eggplant", "a purple eggplant aubergine vegetable with a friendly cartoon face", "vegetables", ["food"], ["vegetable", "purple"]],
  ["Mushroom", "a brown-capped mushroom with a friendly cartoon face, an ordinary mushroom not a game character", "vegetables", ["food"], ["vegetable"]],
  ["Pumpkin", "an orange pumpkin with a friendly cartoon face", "vegetables", ["food", "halloween"], ["vegetable", "orange", "halloween"]],
  ["Onion", "a white onion with papery skin and a friendly cartoon face", "vegetables", ["food"], ["vegetable"]],
  ["Cucumber", "a green cucumber with a friendly cartoon face", "vegetables", ["food"], ["vegetable", "green"]],
  ["Lettuce", "a leafy green lettuce with a friendly cartoon face", "vegetables", ["food"], ["vegetable", "green", "healthy"]],
  ["Sweet Potato", "an orange sweet potato with a friendly cartoon face", "vegetables", ["food"], ["vegetable"]],
  ["Peas", "a green pea pod with peas and a friendly cartoon face", "vegetables", ["food"], ["vegetable", "green"]],
  ["Chilli Pepper", "a red hot chilli pepper with a friendly cartoon face", "vegetables", ["food"], ["vegetable", "spicy", "red"]],
  ["Garlic", "a white garlic bulb with a friendly cartoon face", "vegetables", ["food"], ["vegetable"]],

  // --- prepared food & drink -----------------------------------------------
  ["Pizza Slice", "a triangular slice of pepperoni pizza with a friendly cartoon face", "food", ["food"], ["pizza", "fast-food"]],
  ["Hamburger", "a stacked cheeseburger with a friendly cartoon face", "food", ["food"], ["burger", "fast-food"]],
  ["French Fries", "a carton of golden french fries with a friendly cartoon face", "food", ["food"], ["fries", "fast-food"]],
  ["Hot Dog Snack", "a hot dog in a bun with mustard and a friendly cartoon face, a food item not an animal", "food", ["food"], ["fast-food"]],
  ["Coffee Cup", "a takeaway coffee cup with steam and a friendly cartoon face", "drinks", ["food"], ["coffee", "drink"]],
  ["Ice Cream Cone", "a soft-serve ice cream cone with a friendly cartoon face", "desserts", ["food"], ["dessert", "sweet"]],
  ["Birthday Cake", "a decorated birthday cake with candles and a friendly cartoon face", "desserts", ["food", "birthday"], ["dessert", "birthday"]],
  ["Donut", "a pink-frosted donut with sprinkles and a friendly cartoon face", "desserts", ["food", "bakery"], ["dessert", "bakery"]],
  ["Taco", "a folded taco with fillings and a friendly cartoon face", "food", ["food"], ["fast-food"]],
  ["Sushi Roll", "a sushi roll piece with a friendly cartoon face", "food", ["food"], ["japanese"]],
  ["Croissant", "a golden croissant pastry with a friendly cartoon face", "bakery", ["food"], ["bakery"]],
  ["Bread Loaf", "a crusty loaf of bread with a friendly cartoon face", "bakery", ["food"], ["bakery"]],
  ["Cupcake", "a frosted cupcake with a friendly cartoon face", "desserts", ["food", "bakery"], ["dessert", "sweet"]],
  ["Milkshake", "a tall milkshake glass with whipped cream and a friendly cartoon face", "drinks", ["food"], ["drink", "sweet"]],
  ["Smoothie", "a fruit smoothie in a glass with a friendly cartoon face", "drinks", ["food"], ["drink", "healthy"]],
  ["Tea Cup", "a teacup with steam and a friendly cartoon face", "drinks", ["food"], ["drink"]],
  ["Pretzel", "a salted pretzel with a friendly cartoon face", "bakery", ["food"], ["bakery", "snack"]],
  ["Popcorn", "a striped popcorn bucket overflowing with popcorn, with a friendly cartoon face", "food", ["food"], ["snack", "cinema"]],

  // --- dragons ---------------------------------------------------------------
  ["Red Dragon", "an original fierce red scaled dragon head with horns", "dragons", ["fantasy"], ["dragon", "fire", "red"]],
  ["Ice Dragon", "an original pale blue ice dragon head with frost-covered horns", "dragons", ["fantasy"], ["dragon", "ice", "blue"]],
  ["Golden Dragon", "an original golden scaled dragon head with ornate horns", "dragons", ["fantasy"], ["dragon", "gold"]],
  ["Baby Dragon", "an original cute small green baby dragon with big eyes", "dragons", ["fantasy"], ["dragon", "cute"]],
  ["Shadow Dragon", "an original dark purple shadow dragon head with glowing eyes", "dragons", ["fantasy"], ["dragon", "dark"]],
  ["Forest Dragon", "an original green forest dragon head with mossy scales and antlers", "dragons", ["fantasy"], ["dragon", "green"]],
  ["Storm Dragon", "an original storm-grey dragon head crackling with lightning", "dragons", ["fantasy"], ["dragon", "storm"]],
  ["Wyvern", "an original two-legged wyvern head with leathery wings behind", "dragons", ["fantasy"], ["dragon", "wyvern"]],

  // --- warriors & warlords ---------------------------------------------------
  ["Warlord", "an original armoured warlord with a battle-scarred helmet, generic fantasy design", "warriors", ["fantasy"], ["warlord", "armour"]],
  ["Barbarian Warlord", "an original fur-clad barbarian warlord with braided beard", "warriors", ["fantasy"], ["warlord", "barbarian"]],
  ["Armoured Knight", "an original medieval knight in polished plate armour with visor raised", "warriors", ["historical"], ["knight", "armour"]],
  ["Viking Warrior", "an original viking warrior with horned-free helmet and braided beard", "warriors", ["historical"], ["viking"]],
  ["Samurai", "an original samurai warrior in traditional armour and helmet", "warriors", ["historical"], ["samurai"]],
  ["Gladiator", "an original roman gladiator with crested helmet", "warriors", ["historical"], ["gladiator"]],
  ["Spartan Warrior", "an original spartan hoplite with crested bronze helmet", "warriors", ["historical"], ["spartan"]],
  ["Archer Ranger", "an original hooded forest ranger archer with a bow", "warriors", ["fantasy"], ["archer", "ranger"]],
  ["Shieldmaiden", "an original female norse shieldmaiden warrior with braided hair", "warriors", ["fantasy"], ["warrior", "female"]],
  ["Desert Nomad Warrior", "an original desert nomad warrior with wrapped headscarf", "warriors", ["fantasy"], ["warrior", "desert"]],

  // --- wizards, witches, fantasy folk ---------------------------------------
  ["Wizard", "an original old wizard with long white beard and pointed hat, generic fantasy design", "wizards", ["fantasy"], ["wizard", "magic"]],
  ["Sorceress", "an original female sorceress with glowing magical aura", "wizards", ["fantasy"], ["witch", "magic", "female"]],
  ["Witch", "an original green-hatted witch with a warm smile", "wizards", ["halloween"], ["witch", "halloween"]],
  ["Warlock", "an original dark warlock in hooded robes with arcane runes", "wizards", ["fantasy"], ["warlock", "magic"]],
  ["Elf Archer", "an original pointed-ear elf archer with long hair", "fantasy", ["warriors"], ["elf"]],
  ["Orc Chieftain", "an original green-skinned orc chieftain with tusks", "monsters", ["fantasy"], ["orc"]],
  ["Dwarf Blacksmith", "an original stout dwarf blacksmith with a thick braided beard", "fantasy", ["characters"], ["dwarf"]],
  ["Forest Fairy", "an original tiny forest fairy with translucent wings", "fantasy", ["characters"], ["fairy"]],
  ["Phoenix", "an original flaming phoenix bird with fiery plumage", "fantasy-animals", ["fantasy"], ["phoenix", "fire"]],
  ["Unicorn", "an original white unicorn head with a spiral horn and flowing mane", "fantasy-animals", ["fantasy"], ["unicorn"]],
  ["Griffin", "an original griffin with eagle head and lion body", "fantasy-animals", ["fantasy"], ["griffin"]],
  ["Mermaid", "an original mermaid with flowing hair and shimmering scales", "mermaids", ["fantasy"], ["mermaid", "ocean"]],
  ["Merman", "an original merman with a trident and shimmering scales", "mermaids", ["fantasy"], ["merman", "ocean"]],
  ["Centaur", "an original centaur with a human torso and horse body", "fantasy", ["characters"], ["centaur"]],
  ["Minotaur", "an original minotaur with bull horns and a nose ring", "monsters", ["fantasy"], ["minotaur"]],
  ["Troll", "an original lumbering troll with mossy skin", "monsters", ["fantasy"], ["troll"]],
  ["Goblin", "an original small green goblin with pointed ears and a mischievous grin", "monsters", ["fantasy"], ["goblin"]],
  ["Genie", "an original blue genie emerging from a lamp, original design", "fantasy", ["characters"], ["genie", "magic"]],

  // --- monsters, undead, halloween ------------------------------------------
  ["Vampire", "an original vampire with pale skin, fangs and a high collar", "monsters", ["halloween"], ["vampire", "halloween"]],
  ["Zombie", "an original friendly cartoon zombie with tattered clothes", "monsters", ["halloween"], ["zombie", "halloween"]],
  ["Friendly Ghost", "an original translucent white ghost with a cheerful face", "monsters", ["halloween"], ["ghost", "halloween"]],
  ["Werewolf", "an original werewolf with fur and glowing eyes", "monsters", ["halloween"], ["werewolf"]],
  ["Mummy", "an original bandaged mummy with glowing eyes", "monsters", ["halloween"], ["mummy", "halloween"]],
  ["Frankenstein Monster", "an original tall green stitched monster with bolts, generic design", "monsters", ["halloween"], ["monster", "halloween"]],
  ["Skeleton", "an original friendly cartoon skeleton skull", "monsters", ["halloween"], ["skeleton", "halloween"]],
  ["Swamp Creature", "an original scaly green swamp creature", "monsters", ["fantasy"], ["monster"]],
  ["Yeti", "an original white furry yeti with a gentle expression", "monsters", ["fantasy"], ["yeti"]],
  ["Kraken", "an original giant tentacled sea kraken", "monsters", ["fantasy"], ["kraken", "ocean"]],

  // --- heroes, villains, sci-fi ---------------------------------------------
  ["Superhero", "an ORIGINAL generic superhero in a red and gold suit with a cape and simple mask, not resembling any existing comic character", "superheroes", ["characters"], ["superhero"]],
  ["Super Heroine", "an ORIGINAL generic female superhero in a teal suit with a cape, not resembling any existing comic character", "superheroes", ["characters"], ["superhero", "female"]],
  ["Supervillain", "an ORIGINAL generic supervillain with a dark hooded costume, not resembling any existing comic character", "villains", ["characters"], ["villain"]],
  ["Masked Vigilante", "an ORIGINAL masked vigilante in dark armour, not resembling any existing comic character", "superheroes", ["characters"], ["hero"]],
  ["Friendly Robot", "an original rounded friendly robot with glowing eyes", "robots", ["sci-fi"], ["robot"]],
  ["Battle Mech", "an original heavy battle mech head with armour plating", "robots", ["sci-fi"], ["robot", "mech"]],
  ["Android Assistant", "an original sleek humanoid android with a calm face", "robots", ["sci-fi"], ["android"]],
  ["Alien Visitor", "an original grey alien with large dark eyes", "aliens", ["sci-fi"], ["alien"]],
  ["Insect Alien", "an original insectoid alien with compound eyes", "aliens", ["sci-fi"], ["alien"]],
  ["Space Explorer", "an original astronaut in a white spacesuit with reflective visor", "aliens", ["sci-fi"], ["astronaut", "space"]],
  ["Cyberpunk Hacker", "an original cyberpunk hacker with neon visor", "robots", ["sci-fi"], ["cyberpunk"]],

  // --- royalty, pirates, cowboys, historical --------------------------------
  ["King", "an original medieval king with a golden crown and fur-trimmed robe", "royalty", ["historical"], ["king", "crown"]],
  ["Queen", "an original medieval queen with an ornate crown", "royalty", ["historical"], ["queen", "crown", "female"]],
  ["Princess", "an ORIGINAL fantasy princess with a simple tiara, not resembling any existing cartoon or game princess", "royalty", ["fantasy"], ["princess", "female"]],
  ["Prince", "an original young prince with a circlet and cape", "royalty", ["fantasy"], ["prince"]],
  ["Pirate Captain", "an original pirate captain with tricorn hat and beard", "pirates", ["historical"], ["pirate"]],
  ["Pirate First Mate", "an original pirate with a bandana and eye patch", "pirates", ["historical"], ["pirate"]],
  ["Cowboy", "an original cowboy with a wide-brimmed hat and bandana", "cowboys", ["historical"], ["cowboy", "western"]],
  ["Cowgirl", "an original cowgirl with a hat and braided hair", "cowboys", ["historical"], ["cowgirl", "western", "female"]],
  ["Sheriff", "an original old-west sheriff with a star badge", "cowboys", ["police"], ["sheriff", "western"]],
  ["Egyptian Pharaoh", "an original egyptian pharaoh with a striped nemes headdress", "historical", ["royalty"], ["egyptian"]],
  ["Roman Senator", "an original roman senator in a toga with laurel wreath", "historical", ["characters"], ["roman"]],
  ["Victorian Gentleman", "an original victorian gentleman with a top hat and moustache", "historical", ["characters"], ["victorian"]],
  ["Renaissance Painter", "an original renaissance painter with a beret and palette", "historical", ["characters"], ["renaissance"]],
  ["Caveman", "an original friendly caveman with fur clothing and a club", "historical", ["characters"], ["caveman"]],
  ["Ninja", "an original masked ninja in dark garb", "warriors", ["historical"], ["ninja"]],

  // --- animals ---------------------------------------------------------------
  ["Golden Retriever", "a friendly golden retriever dog head", "dogs", ["animals"], ["dog", "pet"]],
  ["French Bulldog", "a french bulldog head with bat ears", "dogs", ["animals"], ["dog", "pet"]],
  ["Husky", "a siberian husky dog head with blue eyes", "dogs", ["animals"], ["dog", "pet"]],
  ["Dachshund", "a dachshund sausage dog head with long ears", "dogs", ["animals"], ["dog", "pet"]],
  ["Tabby Cat", "a tabby cat head with green eyes", "cats", ["animals"], ["cat", "pet"]],
  ["Black Cat", "a sleek black cat head with amber eyes", "cats", ["animals", "halloween"], ["cat", "halloween"]],
  ["Persian Cat", "a fluffy white persian cat head", "cats", ["animals"], ["cat", "pet"]],
  ["Lion", "a majestic male lion head with a full mane", "jungle-animals", ["animals"], ["lion"]],
  ["Tiger", "a bengal tiger head with orange and black stripes", "jungle-animals", ["animals"], ["tiger"]],
  ["Elephant", "an elephant head with large ears and tusks", "jungle-animals", ["animals"], ["elephant"]],
  ["Giraffe", "a giraffe head with patterned coat and small horns", "jungle-animals", ["animals"], ["giraffe"]],
  ["Monkey", "a cheeky monkey head with expressive eyes", "jungle-animals", ["animals"], ["monkey"]],
  ["Panda", "a giant panda head with black eye patches", "jungle-animals", ["animals"], ["panda"]],
  ["Brown Bear", "a brown bear head with a gentle expression", "jungle-animals", ["animals"], ["bear"]],
  ["Red Fox", "a red fox head with pointed ears", "jungle-animals", ["animals"], ["fox"]],
  ["Grey Wolf", "a grey wolf head with amber eyes", "jungle-animals", ["animals"], ["wolf"]],
  ["Wise Owl", "a wise owl head with large round eyes", "birds", ["animals"], ["owl", "bird"]],
  ["Bald Eagle", "a bald eagle head with a hooked beak", "birds", ["animals"], ["eagle", "bird"]],
  ["Parrot", "a colourful macaw parrot head", "birds", ["animals"], ["parrot", "bird"]],
  ["Penguin", "an emperor penguin head with orange markings", "birds", ["animals"], ["penguin", "bird"]],
  ["Rooster", "a rooster head with a red comb", "birds", ["farm-animals"], ["rooster", "farm"]],
  ["Dolphin", "a bottlenose dolphin head with a friendly smile", "ocean-animals", ["animals"], ["dolphin", "ocean"]],
  ["Great White Shark", "a great white shark head with a toothy grin", "ocean-animals", ["animals"], ["shark", "ocean"]],
  ["Sea Turtle", "a sea turtle head with patterned shell behind", "ocean-animals", ["animals"], ["turtle", "ocean"]],
  ["Octopus", "an octopus head with curling tentacles", "ocean-animals", ["animals"], ["octopus", "ocean"]],
  ["Whale", "a humpback whale head with a gentle expression", "ocean-animals", ["animals"], ["whale", "ocean"]],
  ["Crab", "a red crab with raised claws and a cheerful face", "ocean-animals", ["animals"], ["crab", "ocean"]],
  ["Farm Cow", "a black and white dairy cow head", "farm-animals", ["animals"], ["cow", "farm"]],
  ["Pig", "a pink pig head with a snout", "farm-animals", ["animals"], ["pig", "farm"]],
  ["Sheep", "a woolly sheep head", "farm-animals", ["animals"], ["sheep", "farm"]],
  ["Horse", "a chestnut horse head with a flowing mane", "farm-animals", ["animals"], ["horse", "farm"]],
  ["Goat", "a goat head with curved horns", "farm-animals", ["animals"], ["goat", "farm"]],
  ["Rabbit", "a fluffy rabbit head with long ears", "farm-animals", ["animals", "easter"], ["rabbit", "easter"]],

  // --- dinosaurs -------------------------------------------------------------
  ["T-Rex", "a tyrannosaurus rex head with sharp teeth", "dinosaurs", ["animals"], ["dinosaur"]],
  ["Triceratops", "a triceratops head with three horns and a frill", "dinosaurs", ["animals"], ["dinosaur"]],
  ["Velociraptor", "a feathered velociraptor head", "dinosaurs", ["animals"], ["dinosaur"]],
  ["Stegosaurus", "a stegosaurus head with back plates visible", "dinosaurs", ["animals"], ["dinosaur"]],
  ["Brachiosaurus", "a long-necked brachiosaurus head", "dinosaurs", ["animals"], ["dinosaur"]],
  ["Pterodactyl", "a pterodactyl head with a crested skull", "dinosaurs", ["animals"], ["dinosaur"]],

  // --- vehicles ---------------------------------------------------------------
  ["Race Car", "a red race car front with headlight eyes and a grille smile", "cars", ["vehicles"], ["car", "racing"]],
  ["Family Car", "a blue family hatchback car front with headlight eyes", "cars", ["vehicles"], ["car"]],
  ["Pickup Truck", "a pickup truck front with headlight eyes and a friendly grille", "trucks", ["vehicles"], ["truck"]],
  ["Delivery Van", "a white delivery van front with headlight eyes", "trucks", ["vehicles"], ["van", "delivery"]],
  ["Semi Truck", "a chrome semi truck cab front with headlight eyes", "trucks", ["vehicles"], ["truck"]],
  ["Motorcycle", "a motorcycle front with headlight eye and handlebars", "motorcycles", ["vehicles"], ["motorcycle"]],
  ["Sailboat", "a small sailboat with a friendly face on the hull", "boats", ["vehicles"], ["boat"]],
  ["Speedboat", "a speedboat front with a cheerful face", "boats", ["vehicles"], ["boat"]],
  ["Passenger Jet", "a passenger airplane front with cockpit-window eyes", "airplanes", ["vehicles"], ["airplane"]],
  ["Helicopter", "a helicopter front with windscreen eyes", "airplanes", ["vehicles"], ["helicopter"]],
  ["Excavator", "a yellow excavator with a friendly face on the cab", "construction-equipment", ["vehicles", "construction"], ["excavator"]],
  ["Bulldozer", "a yellow bulldozer with a friendly face", "construction-equipment", ["vehicles", "construction"], ["bulldozer"]],
  ["Cement Mixer", "a cement mixer truck with a friendly face", "construction-equipment", ["vehicles", "construction"], ["mixer"]],
  ["Farm Tractor", "a green farm tractor with a friendly face", "farm-equipment", ["vehicles", "agriculture"], ["tractor", "farm"]],
  ["Combine Harvester", "a combine harvester with a friendly face", "farm-equipment", ["vehicles", "agriculture"], ["harvester", "farm"]],
  ["Ambulance", "an ambulance front with headlight eyes and a caring expression", "emergency-vehicles", ["vehicles"], ["ambulance", "emergency"]],
  ["Fire Engine", "a red fire engine front with headlight eyes", "emergency-vehicles", ["vehicles", "firefighters"], ["fire truck", "emergency"]],
  ["Police Car", "a police car front with headlight eyes and a light bar", "emergency-vehicles", ["vehicles", "police"], ["police car", "emergency"]],
  ["School Bus", "a yellow school bus front with headlight eyes", "trucks", ["vehicles", "education"], ["bus", "school"]],

  // --- holidays & occasions ---------------------------------------------------
  ["Santa Claus", "a jolly santa claus with white beard and red hat", "christmas", ["holiday"], ["santa", "christmas"]],
  ["Mrs Claus", "a cheerful mrs claus with white hair and red bonnet", "christmas", ["holiday"], ["christmas", "female"]],
  ["Christmas Elf", "a christmas elf with pointed ears and a green hat", "christmas", ["holiday"], ["elf", "christmas"]],
  ["Reindeer", "a reindeer head with antlers and a red nose", "christmas", ["holiday", "animals"], ["reindeer", "christmas"]],
  ["Snowman", "a cheerful snowman with a carrot nose and top hat", "christmas", ["holiday"], ["snowman", "christmas"]],
  ["Gingerbread Man", "a gingerbread man cookie with icing and a happy face", "christmas", ["holiday", "desserts"], ["gingerbread", "christmas"]],
  ["Jack O Lantern", "a carved orange jack-o-lantern with a glowing grin", "halloween", ["holiday"], ["pumpkin", "halloween"]],
  ["Cupid", "a cherubic cupid with small wings and a bow", "valentines", ["holiday"], ["cupid", "valentine"]],
  ["Heart Character", "a red heart shape with a cheerful cartoon face", "valentines", ["holiday"], ["heart", "valentine"]],
  ["Thanksgiving Turkey", "a plump turkey with fanned tail feathers and a friendly face", "thanksgiving", ["holiday", "birds"], ["turkey", "thanksgiving"]],
  ["Easter Bunny", "an easter bunny holding a decorated egg", "easter", ["holiday"], ["bunny", "easter"]],
  ["Easter Egg", "a decorated pastel easter egg with a cheerful face", "easter", ["holiday"], ["egg", "easter"]],
  ["New Year Party Popper", "a party popper bursting with confetti, with a cheerful face", "new-year", ["holiday"], ["party", "new year"]],
  ["Bride", "an original smiling bride in a white veil", "wedding", ["holiday"], ["bride", "wedding", "female"]],
  ["Groom", "an original smiling groom in a formal suit and bow tie", "wedding", ["holiday"], ["groom", "wedding"]],
  ["Birthday Balloon", "a colourful birthday balloon bunch with a cheerful face", "birthday", ["holiday"], ["balloon", "birthday"]],
  ["Graduate", "an original graduate in cap and gown holding a diploma", "graduation", ["holiday", "education"], ["graduate", "graduation"]],

  // --- mascots -----------------------------------------------------------------
  ["Sports Team Bear", "an original sports mascot bear in a team jersey", "sports-mascots", ["mascots"], ["mascot", "sports"]],
  ["Sports Team Eagle", "an original sports mascot eagle in team colours", "sports-mascots", ["mascots"], ["mascot", "sports"]],
  ["Sports Team Bull", "an original sports mascot bull with a nose ring and jersey", "sports-mascots", ["mascots"], ["mascot", "sports"]],
  ["School Owl Mascot", "an original school mascot owl wearing a graduation cap", "school-mascots", ["mascots", "education"], ["mascot", "school"]],
  ["School Lion Mascot", "an original school mascot lion in a varsity jacket", "school-mascots", ["mascots", "education"], ["mascot", "school"]],
  ["Delivery Mascot", "an original friendly delivery-company mascot character in a cap", "business-mascots", ["mascots"], ["mascot", "business"]],
  ["Coffee Shop Mascot", "an original cheerful coffee-shop mascot bean character", "business-mascots", ["mascots", "drinks"], ["mascot", "coffee"]],
  ["Bank Mascot", "an original trustworthy bank mascot character in a suit", "business-mascots", ["mascots", "finance"], ["mascot", "finance"]],
  ["Gym Mascot", "an original muscular gym mascot character with a sweatband", "business-mascots", ["mascots", "fitness"], ["mascot", "fitness"]],

  // --- trades & professions the presenter catalog lacks -----------------------
  ["HVAC Technician", "an original HVAC technician in work uniform with a cap", "hvac", ["construction"], ["hvac", "trade"]],
  ["Plumber", "an original plumber in overalls holding a wrench", "plumbing", ["construction"], ["plumber", "trade"]],
  ["Electrician", "an original electrician in a hard hat with cable over shoulder", "electrical", ["construction"], ["electrician", "trade"]],
  ["Roofer", "an original roofer in a hard hat and tool belt", "roofing", ["construction"], ["roofer", "trade"]],
  ["Carpenter", "an original carpenter with a tool belt and pencil behind the ear", "carpentry", ["construction"], ["carpenter", "trade"]],
  ["Welder", "an original welder with a raised welding mask", "manufacturing", ["construction"], ["welder", "trade"]],
  ["Mechanic", "an original car mechanic in overalls holding a spanner", "automotive", ["manufacturing"], ["mechanic", "trade"]],
  ["Farmer", "an original farmer in a straw hat and checked shirt", "agriculture", ["characters"], ["farmer"]],
  ["Chef", "an original chef in a white jacket and toque", "restaurants", ["hospitality"], ["chef"]],
  ["Barista", "an original barista in an apron holding a cup", "restaurants", ["hospitality", "drinks"], ["barista"]],
  ["Police Officer", "an original police officer in uniform with a peaked cap", "police", ["government"], ["police"]],
  ["Firefighter", "an original firefighter in a helmet and turnout gear", "firefighters", ["government"], ["firefighter"]],
  ["Paramedic", "an original paramedic in uniform with a medical bag", "firefighters", ["healthcare"], ["paramedic"]],
  ["Soldier", "an original soldier in plain camouflage uniform and beret", "military", ["government"], ["soldier"]],
  ["Pilot", "an original airline pilot in uniform with a peaked cap", "travel", ["characters"], ["pilot"]],
  ["Flight Attendant", "an original flight attendant in uniform with a neck scarf", "travel", ["hospitality"], ["cabin crew"]],
  ["Scientist", "an original scientist in a lab coat holding a flask", "scientists", ["technology"], ["scientist"]],
  ["Engineer", "an original engineer in a hard hat holding blueprints", "engineers", ["construction"], ["engineer"]],
  ["Teacher", "an original teacher holding a book in front of a chalkboard", "education", ["characters"], ["teacher"]],
  ["Nurse", "an original nurse in scrubs with a stethoscope", "healthcare", ["characters"], ["nurse"]],
  ["Doctor", "an original doctor in a white coat with a stethoscope", "healthcare", ["business"], ["doctor"]],
  ["Dentist", "an original dentist in scrubs with a dental mirror", "healthcare", ["characters"], ["dentist"]],
  ["Veterinarian", "an original veterinarian in scrubs holding a puppy", "healthcare", ["animals"], ["vet"]],
  ["Lawyer", "an original lawyer in a suit holding a legal file", "legal", ["business"], ["lawyer"]],
  ["Judge", "an original judge in black robes with a gavel", "legal", ["government"], ["judge"]],
  ["Real Estate Agent", "an original real estate agent in a blazer holding a For Sale sign", "real-estate", ["business", "sales"], ["realtor"]],
  ["Banker", "an original banker in a suit at a desk", "finance", ["business"], ["banker"]],
  ["Insurance Agent", "an original insurance agent in a suit with a clipboard", "insurance", ["business"], ["insurance"]],
  ["Retail Assistant", "an original retail shop assistant in a branded polo shirt", "retail", ["sales"], ["retail"]],
  ["Hair Stylist", "an original hair stylist holding scissors and a comb", "beauty", ["characters"], ["stylist"]],
  ["Makeup Artist", "an original makeup artist holding a brush and palette", "beauty", ["characters"], ["makeup"]],
  ["Personal Trainer", "an original personal trainer in athletic wear with a towel", "fitness", ["characters"], ["trainer"]],
  ["Yoga Instructor", "an original yoga instructor in athletic wear, calm expression", "fitness", ["characters"], ["yoga"]],
  ["News Anchor", "an original news anchor in a suit at a news desk", "news-media", ["business"], ["news"]],
  ["Field Reporter", "an original field reporter holding a microphone", "news-media", ["characters"], ["reporter"]],
  ["Customer Service Agent", "an original customer service agent wearing a headset", "customer-service", ["business"], ["support"]],
  ["Sales Executive", "an original sales executive in a suit with a confident smile", "sales", ["business"], ["sales"]],
  ["Software Developer", "an original software developer at a laptop with headphones", "technology", ["business"], ["developer"]],
  ["IT Support Technician", "an original IT technician holding a network cable", "technology", ["customer-service"], ["it"]],
  ["Government Official", "an original government official in a suit with a lapel pin", "government", ["business"], ["government"]],
  ["Warehouse Worker", "an original warehouse worker in hi-vis with a scanner", "manufacturing", ["retail"], ["warehouse"]],
  ["Construction Foreman", "an original construction foreman in a hard hat with plans", "construction", ["engineers"], ["foreman"]],

  // --- people & life stages ---------------------------------------------------
  ["Young Boy", "an original cheerful young boy cartoon character", "children", ["families"], ["child", "boy"]],
  ["Young Girl", "an original cheerful young girl cartoon character", "children", ["families"], ["child", "girl", "female"]],
  ["Toddler", "an original happy toddler cartoon character", "children", ["families"], ["toddler"]],
  ["Teen Boy", "an original teenage boy with a friendly expression", "teens", ["families"], ["teen"]],
  ["Teen Girl", "an original teenage girl with a friendly expression", "teens", ["families"], ["teen", "female"]],
  ["Young Mother", "an original young mother holding a baby", "families", ["people"], ["mother", "female"]],
  ["Young Father", "an original young father with a warm smile", "families", ["people"], ["father"]],
  ["Grandmother", "an original kind grandmother with grey hair and glasses", "seniors", ["families"], ["senior", "female"]],
  ["Grandfather", "an original kind grandfather with grey hair and a cardigan", "seniors", ["families"], ["senior"]],
  ["Senior Athlete", "an original active senior in sportswear", "seniors", ["fitness"], ["senior"]],
];
