import Link from "next/link";
import Image from "next/image";
import BusinessShell from "@/components/design/BusinessShell";
import BIcon, { type IconKey } from "@/components/design/BIcon";
import { getOverview, timeAgo } from "@/lib/business";

export const metadata = { title: "Business Center — Reelo" };

// Read per request: these are the signed-in customer's own figures, so they
// must never be cached and served to somebody else.
export const dynamic = "force-dynamic";

function Skyline() {
  return (
    <svg viewBox="0 0 1200 120" preserveAspectRatio="none" className="absolute inset-x-0 bottom-0 h-24 w-full opacity-40" aria-hidden>
      <g fill="rgba(120,12,18,.5)">
        {Array.from({ length: 40 }).map((_, i) => {
          const w = 22 + ((i * 17) % 20);
          const h = 30 + ((i * 53) % 70);
          return <rect key={i} x={i * 30} y={120 - h} width={w} height={h} />;
        })}
      </g>
    </svg>
  );
}

const STAT_ICONS: IconKey[] = ["film", "eye", "heart", "growth", "dollar"];

const CARDS: { n: number; icon: IconKey; art: string; title: string; desc: string; badge?: string; href: string }[] = [
  { n: 1, icon: "pen", art: "create", title: "Create", desc: "Make amazing videos in minutes.", href: "/create" },
  { n: 2, icon: "film", art: "video-library", title: "Video Library", desc: "Manage and organize all your creations.", href: "/library" },
  { n: 3, icon: "palette", art: "brand-kit", title: "Brand Kit", desc: "Store your logos, colors, fonts, and brand assets.", href: "/business-center/brand-kit" },
  { n: 4, icon: "folder", art: "assets", title: "Assets", desc: "Access and manage all your media and resources.", badge: "NEW", href: "/business-center/assets" },
  { n: 5, icon: "share", art: "social", title: "Social", desc: "Connect and grow your social channels.", badge: "SOON", href: "/business-center/social" },
  { n: 6, icon: "rocket", art: "publishing", title: "Publishing", desc: "Publish your content everywhere.", badge: "SOON", href: "/business-center/publishing" },
  { n: 7, icon: "calendar", art: "scheduling", title: "Scheduling", desc: "Schedule posts and never miss a beat.", badge: "SOON", href: "/business-center/scheduling" },
  { n: 8, icon: "chart", art: "analytics", title: "Analytics", desc: "Track performance and grow faster.", badge: "SOON", href: "/business-center/analytics" },
  { n: 9, icon: "dollar", art: "revenue", title: "Revenue", desc: "Monitor earnings and growth.", badge: "SOON", href: "/business-center/revenue" },
  { n: 10, icon: "brain", art: "trend-ai", title: "Trend AI", desc: "Discover trending topics and ideas.", badge: "SOON", href: "/trends" },
  { n: 11, icon: "crown", art: "hub-pro", title: "Hub Pro", desc: "Unlock all pro tools and advanced features.", badge: "SOON", href: "/business-center/pro" },
];

// Every one of these goes to something that works. The old set listed "Video to
// Script" and "Clone Video", which are not tools Reelo has, and none of the six
// were links at all.
const QUICK: { icon: IconKey; label: string; href: string }[] = [
  { icon: "film", label: "New Video", href: "/create" },
  { icon: "upload", label: "Upload Media", href: "/business-center/assets" },
  { icon: "bolt", label: "Create Short", href: "/create/shorts-20" },
  { icon: "users", label: "AI Avatar", href: "/create/ai-avatar-studio" },
  { icon: "doc", label: "Storybook", href: "/create/bedtime-storybook" },
  { icon: "refresh", label: "Product Ad", href: "/create/product-commercial" },
];

const FOOTER: { icon: IconKey; t: string; d: string }[] = [
  { icon: "layers", t: "All-in-One Platform", d: "Everything you need in one place." },
  { icon: "clock", t: "Save Time", d: "Powerful tools to work smarter." },
  { icon: "growth", t: "Grow Faster", d: "Create more. Engage more. Earn more." },
  { icon: "chip", t: "AI Powered", d: "Next-gen AI to boost your content." },
];

const STATUS: Record<string, string> = { completed: "#5fd08a", failed: "#ff8892", draft: "#9a8b8d" };

/**
 * The card artwork, generated by scripts/generate-tiles.mjs.
 *
 * object-contain, not object-cover. The last time these cards carried pictures
 * they were cropped to roughly a third of the image and had to be reverted. The
 * art is square and so is the frame, so the whole illustration is always shown.
 */
function Tile({ art }: { art: string }) {
  return (
    <div className="relative mb-1.5 grid aspect-[2/1] w-full place-items-center overflow-hidden rounded-xl" style={{ background: "radial-gradient(circle at 50% 40%,rgba(225,29,42,.16),transparent 70%)", border: "1px solid rgba(255,70,85,.12)" }}>
      <Image
        src={"/assets/tiles/wide/" + art + ".webp"}
        alt=""
        width={512}
        height={288}
        className="h-full w-full object-cover"
      />
    </div>
  );
}

export default async function BusinessCenterPage() {
  const { stats, recent, personal, signedIn } = await getOverview();

  return (
    <BusinessShell active="overview" variant="overview">
      {/* header */}
      <div className="relative mb-2.5 overflow-hidden rounded-2xl px-6 py-3 text-center" style={{ border: "1px solid rgba(255,70,85,.18)", background: "radial-gradient(700px 220px at 50% -20%,rgba(225,29,42,.3),transparent 70%),rgba(12,6,8,.6)" }}>
        <Skyline />
        <h1 className="font-display relative text-2xl font-extrabold uppercase tracking-tight sm:text-[32px]">Business Center</h1>
        <p className="relative mt-0.5 text-[12.5px]" style={{ color: "#cabcbe" }}>Everything you need to create, manage, and grow your content empire.</p>
      </div>

      {/* stats — the signed-in customer's own, or dashes. Never invented. */}
      <div className="mb-2.5 grid grid-cols-2 gap-2.5 sm:grid-cols-3 lg:grid-cols-5">
        {stats.map((s, i) => (
          <div key={s.label} className="flex items-center gap-2.5 rounded-xl px-3 py-2.5" style={{ border: "1px solid rgba(255,70,85,.16)", background: "rgba(255,60,75,.03)" }}>
            <BIcon name={STAT_ICONS[i] ?? "film"} size={26} />
            <div>
              <div className="font-display text-xl font-bold leading-none">{s.value}</div>
              <div className="mt-0.5 text-[10.5px]" style={{ color: "#8e7f81" }}>{s.label}</div>
            </div>
          </div>
        ))}
      </div>

      {!personal && (
        <div className="mb-2.5 flex flex-wrap items-center gap-2.5 rounded-lg px-3 py-1.5" style={{ border: "1px solid rgba(255,70,85,.2)", background: "rgba(255,60,75,.04)" }}>
          <p className="flex-1 text-[13.5px] text-white/60">
            {signedIn ? "Your figures will appear here once you make something." : "Sign in to see your own numbers here."}
          </p>
          {!signedIn && (
            <>
              <Link href="/login" className="rounded-lg px-3 py-1.5 text-[12.5px] font-bold text-white" style={{ background: "linear-gradient(135deg,#ff3645,#c4101c)" }}>Sign in</Link>
              <Link href="/signup" className="rounded-lg px-3 py-1.5 text-[12.5px] font-semibold" style={{ color: "#b9a9ab", border: "1px solid rgba(255,70,85,.2)" }}>Create account</Link>
            </>
          )}
        </div>
      )}

      {/* Feature cards — all eleven lead somewhere.
          The design lays these out five across, then six, not as an even grid,
          which is why a plain grid-cols-4 looked nothing like it. Flex with an
          explicit basis reproduces the two rows exactly on wide screens and
          still stacks sensibly on a phone. */}
      <div className="mb-2.5 flex flex-wrap gap-2">
        {CARDS.map((c) => (
          <Link
            key={c.n}
            href={c.href}
            className={`relative block flex-1 rounded-xl p-2.5 transition-all hover:-translate-y-1 hover:border-[rgba(255,70,85,.45)] basis-[calc((100%-0.75rem)/2)] sm:basis-[calc((100%-2.25rem)/4)] ${
              c.n <= 5 ? "lg:basis-[calc((100%-3rem)/5)]" : "lg:basis-[calc((100%-3.75rem)/6)]"
            }`}
            style={{ border: "1px solid rgba(255,70,85,.18)", background: "linear-gradient(180deg,rgba(24,9,12,.5),rgba(10,5,7,.5))" }}
          >
            <span className="absolute left-3 top-3 z-10 grid h-6 w-6 place-items-center rounded-full text-xs font-bold" style={{ border: "1px solid rgba(255,70,85,.5)", color: "#ff5663" }}>{c.n}</span>
            {c.badge && (
              <span className="absolute right-3 top-3 z-10 rounded-md px-1.5 py-0.5 text-[9px] font-bold uppercase" style={c.badge === "NEW" ? { color: "#fff", background: "linear-gradient(135deg,#ff3645,#c4101c)" } : { color: "#c98", background: "rgba(255,255,255,.05)", border: "1px solid rgba(255,255,255,.1)" }}>{c.badge}</span>
            )}
            <Tile art={c.art} />
            <h3 className="font-display text-[14px] font-bold leading-tight">{c.title}</h3>
            <p className="mt-0.5 line-clamp-1 text-[11px] leading-[1.35]" style={{ color: "#9a8b8d" }}>{c.desc}</p>
          </Link>
        ))}
      </div>

      {/* activity / quick / whatsnew */}
      <div className="mb-2.5 grid grid-cols-1 gap-3 lg:grid-cols-3">
        <div className="rounded-xl p-3" style={{ border: "1px solid rgba(255,70,85,.16)", background: "rgba(255,60,75,.03)" }}>
          <div className="mb-3 flex items-center justify-between">
            <span className="font-display font-bold">Recent Activity</span>
            <Link href="/library" className="text-xs hover:underline" style={{ color: "#ff5663" }}>View All</Link>
          </div>
          {recent.length === 0 ? (
            <p className="py-6 text-center text-[12.5px] leading-relaxed" style={{ color: "#8e7f81" }}>
              Nothing yet. Anything you make in{" "}
              <Link href="/create" className="underline underline-offset-2 hover:text-white">Create</Link> shows up here.
            </p>
          ) : (
            <div className="flex flex-col gap-2">
              {recent.map((a) => (
                <div key={a.id} className="flex items-center gap-2">
                  <span className="relative grid h-9 w-9 shrink-0 place-items-center overflow-hidden rounded-lg bg-black/40">
                    {a.mediaUrl && a.kind === "image" ? (
                      // eslint-disable-next-line @next/next/no-img-element
                      <img src={a.mediaUrl} alt="" className="h-full w-full object-cover" />
                    ) : (
                      <BIcon name={a.kind === "video" ? "play" : "image"} size={14} color="#fff" glow={false} />
                    )}
                  </span>
                  <div className="min-w-0 flex-1">
                    <div className="truncate text-[13px] font-semibold">{a.title}</div>
                    <div className="text-[11px]" style={{ color: "#8e7f81" }}>{timeAgo(a.createdAt)} · {a.toolTitle}</div>
                  </div>
                  <span className="rounded-md px-2 py-0.5 text-[10px] font-bold capitalize" style={{ color: STATUS[a.status] ?? "#9a8b8d", background: `${STATUS[a.status] ?? "#9a8b8d"}1f` }}>{a.status}</span>
                </div>
              ))}
            </div>
          )}
        </div>

        <div className="rounded-xl p-3" style={{ border: "1px solid rgba(255,70,85,.16)", background: "rgba(255,60,75,.03)" }}>
          <div className="font-display mb-3 font-bold">Quick Actions</div>
          <div className="grid grid-cols-3 gap-2">
            {QUICK.map((q) => (
              <Link
                key={q.label}
                href={q.href}
                className="flex flex-col items-center gap-1 rounded-lg px-1.5 py-2 text-center transition-colors hover:bg-white/5"
                style={{ border: "1px solid rgba(255,70,85,.14)" }}
              >
                <BIcon name={q.icon} size={20} />
                <span className="text-[11px] font-medium leading-tight">{q.label}</span>
              </Link>
            ))}
          </div>
        </div>

        <div className="flex flex-col rounded-xl p-3" style={{ border: "1px solid rgba(255,70,85,.24)", background: "radial-gradient(360px 160px at 90% 10%,rgba(225,29,42,.2),transparent 70%),rgba(14,6,8,.55)" }}>
          <div className="mb-1 flex items-center justify-between">
            <span className="font-display font-bold">What&apos;s New in Reelo</span>
            <Link href="/roadmap" className="text-xs hover:underline" style={{ color: "#ff5663" }}>Roadmap</Link>
          </div>
          {/* This said NEW for a feature that did not exist, then PLANNED once
              that was corrected. It is NEW again because Assets is now real. */}
          <span className="mt-2 w-fit rounded-md px-2 py-0.5 text-[10px] font-bold" style={{ color: "#fff", background: "linear-gradient(135deg,#ff3645,#c4101c)" }}>NEW</span>
          <div className="font-display mt-1.5 text-xl font-extrabold leading-none">ASSETS<br />MANAGER</div>
          <p className="mt-2 text-[13px]" style={{ color: "#a99a9c" }}>Organize, find, and reuse your media faster than ever.</p>
          <Link href="/business-center/assets" className="mt-3 w-fit rounded-lg px-4 py-2 text-sm font-bold text-white" style={{ background: "linear-gradient(135deg,#ff3645,#c4101c)" }}>Try It Now</Link>
        </div>
      </div>

      {/* footer band */}
      <div className="grid grid-cols-2 gap-2.5 rounded-xl px-3.5 py-2.5 sm:grid-cols-2 lg:grid-cols-4" style={{ border: "1px solid rgba(255,70,85,.2)", background: "rgba(14,6,8,.5)" }}>
        {FOOTER.map((f) => (
          <div key={f.t} className="flex items-center gap-2">
            <span className="grid h-7 w-7 shrink-0 place-items-center rounded-full" style={{ border: "1.5px solid rgba(255,70,85,.4)" }}><BIcon name={f.icon} size={16} /></span>
            <div><div className="text-[12.5px] font-bold leading-tight">{f.t}</div><div className="line-clamp-1 text-[10.5px]" style={{ color: "#8e7f81" }}>{f.d}</div></div>
          </div>
        ))}
      </div>
    </BusinessShell>
  );
}
